build_server:
  hosts:
    35.242.190.134:
      ansible_ssh_private_key_file: /home/elliotbrookse/.ssh/ansible_agents/test
docker_agents:
  hosts:
    35.242.190.134:
      ansible_ssh_private_key_file: /home/elliotbrookse/.ssh/ansible_agents/test
terraform_agents: 
  hosts:
    35.242.190.134:
      ansible_ssh_private_key_file: /home/elliotbrookse/.ssh/ansible_agents/test

