# ungrouped:
#   hosts:
buildInfrastructure:
  hosts:
    34.105.196.152:
      ansible_ssh_private_key_file: /home/elliotbrookse/.ssh/ansible_agents/test
# kubernetes:
#   hosts:

# command for ansible jenkins agent to use later
# ansible-playbook -i hosts /home/ec2-user/ansible/plays/install.yml
