pipeline {
    agent { label 'ansible-agent-1'}
        environment {
        PUBKEY = credentials('agentPubKey')
        }
        stages {
            stage ("Setup") {
                steps {
                    checkout scmGit(
                        branches: [[name: 'main']],
                        userRemoteConfigs: [[url: 'git@github.com:ElliotBre/ansibleConfig.git']])
                        sh "touch hosts.yaml"
                        withCredentials([file(credentialsId: 'ansible-hosts', variable: 'HOSTS')]){
                            sh "cp \$HOSTS hosts.yaml"
                        }
                        sh "touch ansible.cfg"
                        withCredentials([file(credentialsId: 'ansible-config-terraform', variable: 'CONFIG')]){
                            sh "cp \$CONFIG ansible.cfg"
                        }
                }
             }
             stage ("Dry Run") {
                steps {
                  sh "ansible-playbook playbooks/terraform-agent/terraform-agent-setup.yaml --extra-vars \"ssh_public_key='\${PUBKEY}'\" --check"
                }
             }
            //  stage ("Run") {
            //     steps {
            //       sh "ansible-playbook playbooks/terraform-agent/terraform-agent-setup.yaml --extra-vars \"ssh_public_key='\${PUBKEY}'\""
            //     }
            //  }
        }
}
