---
# tasks file for agent-config
- name: Add Jenkins user
  ansible.builtin.user:
    name: jenkins
    home: /home/jenkins
  become: true
- name: Add SSH key
  ansible.builtin.lineinfile:
    dest: /home/jenkins/.ssh/authorized_keys
    state: present
    create: true
    line: "{{ ssh_public_key }}"
  become: true
- name: Adding ssh config for jenkins user
  ansible.builtin.blockinfile:
    dest: /home/jenkins/.ssh/config
    backup: yes
    content: "Host 20.26.156.215
         StrictHostKeyChecking no"
  become: true
- name: Setup visudo perms for Jenkins
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jenkins'
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
