---
# tasks file for agent-config
- name: Add Jenkins user
  ansible.builtin.user:
    name: jenkins
    home: /home/jenkins
    create_home: true
    state: present
  become: true
- name: Setup visudo perms for Jenkins
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jenkins'
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
- name: Create authorized_keys file
  ansible.builtin.file:
    path: /home/jenkins/.ssh/authorized_keys
    state: touch
    owner: jenkins
    mode: '0600'
  become: true
- name: Create ssh config file
  ansible.builtin.file:
    path: /home/jenkins/.ssh/config
    state: touch
    owner: jenkins
    mode: '0600'
  become: true
- name: Add SSH key
  ansible.builtin.lineinfile:
    dest: /home/jenkins/.ssh/authorized_keys
    state: present
    create: true
    line: "{{ ssh_public_key }}"
  become: true
- name: Adding ssh config for jenkins user
  ansible.builtin.blockinfile:
    dest: /home/jenkins/.ssh/config
    backup: yes
    content: "Host 20.26.156.215
         StrictHostKeyChecking no"
  become: true
