---
# tasks file for jenkins
- name: Install Java
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present
  become: true
- name: Install Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    force: true
- name: Add jenkins.list
  lineinfile:
    dest: /etc/apt/sources.list.d/jenkins.list
    state: present
    line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
  become: true
- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
  register: result
  become: true
# - name: Get Jenkins admin password from file.
#   slurp:
#     src: "/var/lib/jenkins/secrets/initialAdminPassword"
#   register: adminpasswordfile
#   no_log: true
#   become: true
# - name: Set Jenkins admin password fact.
#   set_fact:
#     jenkins_admin_password: "{{ adminpasswordfile }}"
  # no_log: true