---
# tasks file for terraform
- name: Install Terraform GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    force: true
  become: true
- name: Add hashicorp repo
  ansible.builtin.apt_repository:
    filename: hashicorp
    repo: 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main'
  become: true
- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true
  become: true
