---
- name: Download Terraform binary
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip"
    dest: "/tmp/terraform_latest.zip"
  become: true
- name: Extract Terraform binary
  ansible.builtin.unarchive:
    src: "/tmp/terraform_latest.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: "-o"
  become: true
- name: Set Terraform permissions
  ansible.builtin.file:
    path: "/usr/local/bin/terraform"
    mode: "0755"
    state: touch
  become: true