---
# tasks file for docker
- name: Install Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    force: true
  become: true
- name: Set docker.asc file perms
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'
  become: true
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true
- name: Give jenkins user docker perms
  ansible.builtin.user:
    name: jenkins
    append: true
    group: docker
  become: true
