---
# tasks file for docker
- name: Install Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    force: true
  become: true
- name: Set docker.asc file perms
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'
  become: true
- name: Add docker.list
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    state: present
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian   bookworm stable"
    create: yes
  become: true
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true
- name: Give jenkins user docker perms
  ansible.builtin.user:
    name: jenkins
    group: docker
  become: true
