- name: Install Jenkins
  hosts: 34.105.196.152

  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: default-jdk
        state: present
    - name: Add Jenkins user
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash
        # home: might have to install this
    - name: Install Jenkins
      ansible.builtin.uri:
        url: 'https://updates.jenkins-ci.org/latest/jenkins.war'
        method: GET
        dest: jenkins.war
        follow_redirects: safe
      register: result
      become: true
      become_user: jenkins
    - name: Config jenkins.service file
      ansible.builtin.blockinfile:
        dest: /etc/systemd/system/jenkins.service
        block: |
          [Unit]
          Description=Jenkins Server

          [Service]
          User=jenkins
          WorkingDirectory=/home/jenkins
          ExecStart=/usr/bin/java -jar /home/jenkins/jenkins.war

          [Install]
          WantedBy=multi-user.target
      become: true
    - name: Restart daemons
      ansible.builtin.systemd_service:
        name: /etc/systemd/system/jenkins.service
        daemon_reload: true
        enabled: true
      become: true
    - name: Get initial admin password
      ansible.builtin.script: ../resources/get-initial-admin-password.sh
      args:
        executable: /bin/bash
      become: true
      become_user: jenkins
      # not sure if we'll need jenkins start step as restart Jenkins should do the job, needs testing
    - name: Start Jenkins
      ansible.builtin.service:
        name: Jenkins
        state: started
        enabled: true
      become: true
      tags: start-jenkins
    # - name: Stop Jenkins
    #   service:
    #     name: Jenkins
    #     status: stopped
    #   become: true
    #   tags: [ never, stop-jenkins ]
